#!/bin/sh

me=poc/main
usg () {
    cat >&2 <<!
$me -n int -o coeff|xy
!
    exit
}

: ${OutputFmt=%+.16e %s%03d}
Lanczos=0
while :
do
    case $# in
	0) break
	   ;;
	*) case "$1" in
	       -h ) usg
		    ;;
	       -l) Lanczos=1
		   ;;
	       -o) shift
		   case $# in
			0) printf %s\\n "$me: -o needs an argument"
			   exit 2
			   ;;
		   esac
		   case "$1" in
		       x*) Output=xy
			   ;;
		       c*) Output=coeff
			   ;;
		       *) printf %s\\n "$me: unknown output type '$1'"
			  exit 2
			  ;;
		   esac
		   ;;
	       -n) shift
		   case $# in
			0) printf %s\\n "$me: -n needs an argument"
			   exit 2
			   ;;
		   esac
		   n=$1
		   ;;
	       -*) printf %s\\n "$me: unknown option '$1'"
		   exit 2
		   ;;
	       *) printf %s\\n "$me: unknown argument '$1'"
		  ;;
	   esac
	   ;;
    esac
    shift
done

case "$n" in
    '') printf %s\\n "$me: -n is not set"
	exit 2
	;;
esac

case "$Output" in
    '') printf %s\\n "$me: -o is not set"
	exit 2
	;;
esac

"${AWK=awk}" -v N="$n" \
-v Lanczos=$Lanczos \
-v Output=$Output \
-v OutputFmt="$OutputFmt" \
'
BEGIN {
    pi = 3.141592653589793
    coeff()
    if (Lanczos)
	lanczos()
    if (Output == "xy")
	output_xy()
    else if (Output == "coeff")
	output_coeff()
}

function f(x,   L) {
    L = 2*N
    #return 1
    #return x/L
    #return abs(sin(2*pi*x/L))
    #return x < L/2 ? x : L - x
    #return x * (L - x)
    return sqrt(x) * (L - x)
    #return x < L/4 ? 0 : x < 3*L/4 ? 1 : 0
    #return sinc(12*pi*(x/L - 1/2))
    #return bump(3*(x/L - 1/2))
}

function output_xy(   lo, hi, n, x, i) {
    lo = 0
    hi = 2 * N
    n = 10 * 2 * N
    for (i = 0; i < n; i++) {
	x = lo + i*(hi - lo)/n
	print x, f(x), g(x)
    }
}

function output_coeff(   m, fmt) {
    fmt = OutputFmt "\n"
    printf fmt, a[0], "a", 0
    for (m = 1; m <= N - 1; m++) {
	printf fmt, a[m], "a", m
	printf fmt, b[m], "b", m
    }
    printf fmt, a[N], "a", N
}

function coeff(   m, x, F, C) {
    for (x = 0; x <= 2 * N - 1; x++)
	F[x] = f(x)
    for (m = 0; m <= N; m++) {
	for (x = 0; x <= 2*N - 1; x++)
	    a[m] += F[x] * cos(pi/N*m*x)
	a[m] /= N
    }
    for (m = 1; m <= N - 1; m++) {
	for (x = 0; x <= 2*N - 1; x++)
	    b[m] += F[x] * sin(pi/N*m*x)
	b[m] /= N
    }
}

function lanczos(   m, sigma) {
    for (m = 1; m <= N; m++) {
	sigma = sin(pi * m / N) / (pi * m / N)
	a[m] *= sigma
	b[m] *= sigma
    }
}

function g(x,   s, m) {
    s = a[0]/2
    for (m = 1; m <= N - 1; m++) {
	s += a[m] * cos(pi/N*m*x)
	s += b[m] * sin(pi/N*m*x)
    }
    s += a[N]/2 * cos(pi*x)
    return s
}

function sq_f(   x, s) {
    for (x = 0; x <= 2*N - 1; x++) {
	s += f(x)^2
    }
    return s
}

function sq_g(   k, s) {
    s = a[0]^2/2
    for (k = 1; k <= N - 1; k++) {
	s += a[k]^2
	s += b[k]^2
    }
    s += a[N]^2/2
    return s * N
}

function abs(x) {
    return x > 0 ? x : -x
}

function sinc(x) {
    eps = 1e-6
    return abs(x) < eps ? 1 - x^2/6 + x^4/120 : sin(x)/x
}

function bump(x) {
    return abs(x) < 1 ? exp(-1/(1 - x^2)) : 0
}
'
